const { allAddons, templates } = require('../server/catalog');
const website = allAddons.filter(a => a.templates === 'all');
const scrapbook = allAddons.filter(a => Array.isArray(a.templates) && a.templates.includes('scrapbook'));
const assert = (ok, message) => { if (!ok) throw new Error(message); };
assert(Object.keys(templates).length === 6, 'Expected 6 templates');
assert(Object.values(templates).every(t => Number(t.price) === 100), 'All templates must be R100');
assert(website.length === 30, `Expected 30 website features, got ${website.length}`);
assert(website.filter(a => a.paid).length === 15, 'Expected 15 paid website features');
assert(scrapbook.length === 50, `Expected 50 scrapbook features, got ${scrapbook.length}`);
assert(scrapbook.filter(a => a.paid).length === 15, 'Expected 15 paid scrapbook features');
console.log('Zapify Supabase catalog validation passed.');
