(async()=>{const el=document.getElementById('hero3d');if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches)return;try{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js');const scene=new THREE.Scene();scene.background=new THREE.Color(0x101015);const camera=new THREE.PerspectiveCamera(42,el.clientWidth/el.clientHeight,.1,100);camera.position.set(0,1.2,6.6);const renderer=new THREE.WebGLRenderer({canvas:el,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(el.clientWidth,el.clientHeight,false);renderer.shadowMap.enabled=true;const group=new THREE.Group();scene.add(group);
 const pink=new THREE.MeshStandardMaterial({color:0xff1688,metalness:.35,roughness:.25});const dark=new THREE.MeshStandardMaterial({color:0x202027,metalness:.65,roughness:.2});const white=new THREE.MeshStandardMaterial({color:0xffffff,metalness:.1,roughness:.35});
 const desk=new THREE.Mesh(new THREE.BoxGeometry(5.8,.22,2.7),dark);desk.position.y=-1.5;desk.receiveShadow=true;group.add(desk);
 const monitor=new THREE.Group();const frame=new THREE.Mesh(new THREE.BoxGeometry(3.7,2.25,.18),dark);frame.castShadow=true;monitor.add(frame);const screen=new THREE.Mesh(new THREE.BoxGeometry(3.4,1.95,.06),new THREE.MeshStandardMaterial({color:0x15151d,emissive:0x09090f}));screen.position.z=.12;monitor.add(screen);monitor.position.set(0,.25,0);group.add(monitor);
 const stand=new THREE.Mesh(new THREE.BoxGeometry(.22,1.15,.22),dark);stand.position.set(0,-.9,0);group.add(stand);const base=new THREE.Mesh(new THREE.BoxGeometry(1.4,.1,.7),dark);base.position.set(0,-1.45,0);group.add(base);
 for(let j=0;j<7;j++){const line=new THREE.Mesh(new THREE.BoxGeometry(1.8-j*.08,.045,.03),new THREE.MeshStandardMaterial({color:j===1||j===4?0xff1688:0x777783,emissive:j===1||j===4?0x50002b:0x000000}));line.position.set(-1.15,-.25+j*.25,.18);screen.add(line)}
 const laptop=new THREE.Mesh(new THREE.BoxGeometry(1.8,.08,1.25),white);laptop.position.set(-1.5,-1.18,.9);laptop.rotation.x=-.08;group.add(laptop);const cube=new THREE.Mesh(new THREE.BoxGeometry(1.7,.8,.04),dark);cube.position.set(-1.5,-.75,.35);cube.rotation.x=-.65;group.add(cube);
 const geo=new THREE.IcosahedronGeometry(.55,1);const orb=new THREE.Mesh(geo,pink);orb.position.set(2,.65,.1);group.add(orb);
 scene.add(new THREE.HemisphereLight(0xffffff,0x222222,2));const light=new THREE.PointLight(0xff1688,16,10);light.position.set(2,2,2);scene.add(light);const whiteLight=new THREE.PointLight(0xffffff,8,10);whiteLight.position.set(-3,3,4);scene.add(whiteLight);
 let mx=0,my=0;el.parentElement.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();mx=(e.clientX-r.left)/r.width-.5;my=(e.clientY-r.top)/r.height-.5});function resize(){const w=el.clientWidth,h=el.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}addEventListener('resize',resize);let t=0;function tick(){t+=.008;group.rotation.y+=((mx*.22)-group.rotation.y)*.03;group.rotation.x+=((-my*.12)-group.rotation.x)*.03;orb.rotation.x+=.012;orb.rotation.y+=.018;renderer.render(scene,camera);requestAnimationFrame(tick)}tick();}catch(e){el.style.display='none';const p=el.parentElement;p.style.background='radial-gradient(circle at 50% 30%,#ff1688,#101015)';}})();
