const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const WA='27743899657';
function quoteUrl(service='Website'){return `https://wa.me/${WA}?text=${encodeURIComponent(`Hi Zapify Designs! I'm interested in ${service}. I'd like to discuss the service and pricing.`)}`}
function init(){
 const header=$('.site-header'); window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>20),{passive:true});
 const menu=$('.menu'), nav=$('.mobile-nav'); menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
 $$('.reveal').forEach(el=>{if(!('IntersectionObserver'in window)||matchMedia('(prefers-reduced-motion: reduce)').matches)el.classList.add('visible');else new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible')}}),{threshold:.1}).observe(el)});
 $$('.quote-link').forEach(a=>a.addEventListener('click',e=>{const s=a.dataset.service;if(s){e.preventDefault();window.open(quoteUrl(s),'_blank','noopener')}}));
 initCursor(); initChat(); initFAQ();
 const params=new URLSearchParams(location.search), svc=params.get('service'); if(svc&&$('#service'))$('#service').value=svc;
}
function initCursor(){const c=$('.cursor'),r=$('.cursor-ring');if(!c||!r||matchMedia('(pointer:coarse)').matches)return;addEventListener('pointermove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px';r.style.left=e.clientX+'px';r.style.top=e.clientY+'px'});$$('a,button,input,select,textarea').forEach(el=>el.addEventListener('mouseenter',()=>r.style.transform='translate(-50%,-50%) scale(1.6)'));$$('a,button,input,select,textarea').forEach(el=>el.addEventListener('mouseleave',()=>r.style.transform='translate(-50%,-50%) scale(1)'))}
function initFAQ(){ $$('.faq details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)$$('.faq details').forEach(x=>{if(x!==d)x.open=false})})) }
const answers=[['price','website','Packages start at R800 for a landing page, with larger builds from R1,250. Custom software and other services are quoted around the scope.'],['seo','google','Zapify can set up technical SEO, on-page SEO, Search Console, Bing Webmaster Tools, sitemaps and local SEO foundations. Rankings are not guaranteed.'],['hosting','domain','Zapify can help with domains, DNS, hosting, SSL, deployment and business email setup.'],['software','dashboard','Yes. Zapify can build database-driven applications, dashboards, customer portals, CRM-style systems, APIs and custom business software.'],['maintenance','support','Maintenance can cover updates, fixes, performance work, security checks and ongoing support. Contact Zapify for a quote.'],['contact','quote','Use the quote form or message Zapify through WhatsApp.']];
function reply(q){q=q.toLowerCase();for(const [a,b,c] of answers)if(q.includes(a)||q.includes(b))return c;return 'I can help with websites, SEO, maintenance, hosting, software, automation, AI, packages and project enquiries. Try asking about pricing, SEO, software, hosting or requesting a quote.'}
function initChat(){const t=$('.chat-toggle'),p=$('.chat'),x=$('.chat-close'),f=$('.chat-form'),i=$('.chat-input'),m=$('.chat-messages');if(!t||!p)return;const add=(txt,who='bot')=>{const d=document.createElement('div');d.className='msg '+who;d.textContent=txt;m.appendChild(d);m.scrollTop=m.scrollHeight};t.onclick=()=>p.classList.toggle('open');x.onclick=()=>p.classList.remove('open');$$('.chat-suggest button').forEach(b=>b.onclick=()=>{i.value=b.textContent;f.requestSubmit()});f.onsubmit=e=>{e.preventDefault();const q=i.value.trim();if(!q)return;add(q,'user');add(reply(q));i.value=''} }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
