(() => {
  const nav = document.getElementById('osNav'), stats = document.getElementById('stats'), view = document.getElementById('view');
  if (!nav || !stats || !view) return;
  const KEY='zapifyOSDataV2';
  const seed={
    customers:[{id:1,name:'Lumi Beauty',contact:'hello@lumibeauty.co.za',status:'Active',value:1800},{id:2,name:'Vaal Auto',contact:'info@vaalauto.co.za',status:'Lead',value:950},{id:3,name:'Casa Vero',contact:'bookings@casavero.co.za',status:'Active',value:2400}],
    leads:[{id:1,name:'Nova Studio',source:'Website',status:'New',value:1200},{id:2,name:'Build Vaal',source:'WhatsApp',status:'Contacted',value:3200}],
    quotes:[{id:1,number:'ZQ-1001',client:'Nova Studio',amount:1250,status:'Draft'},{id:2,number:'ZQ-1002',client:'Build Vaal',amount:3200,status:'Sent'}],
    invoices:[{id:1,number:'INV-1001',client:'Lumi Beauty',amount:1800,status:'Paid'},{id:2,number:'INV-1002',client:'Casa Vero',amount:2400,status:'Pending'}],
    projects:[{id:1,name:'Lumi Beauty website',client:'Lumi Beauty',status:'In progress',progress:72},{id:2,name:'Casa Vero refresh',client:'Casa Vero',status:'Review',progress:90}],
    tasks:[{id:1,title:'Send homepage preview',due:'Today',status:'Open'},{id:2,title:'Publish Casa Vero changes',due:'Tomorrow',status:'Open'}],
    activity:[{text:'Lumi Beauty invoice marked paid',time:'Today'},{text:'Nova Studio added as a lead',time:'Today'},{text:'Casa Vero project moved to Review',time:'Yesterday'}]
  };
  let data=load(); let active='dashboard';
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
  const money=n=>'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const menus=[['dashboard','⌂','Dashboard'],['customers','♙','Customers'],['leads','◉','Leads'],['quotes','▤','Quotes'],['invoices','R','Invoices'],['projects','◆','Projects'],['tasks','✓','Tasks'],['calendar','□','Calendar'],['analytics','↗','Analytics'],['settings','⚙','Settings']];
  const pageMeta={customers:['Customers','Manage contacts and customer records.'],leads:['Leads','Track enquiries from first contact to conversion.'],quotes:['Quotes','Create and track estimates.'],invoices:['Invoices','Track money owed and paid.'],projects:['Projects','Manage delivery and project progress.'],tasks:['Tasks','Keep operational work moving.'],calendar:['Calendar','Your upcoming business schedule.'],analytics:['Analytics','A quick view of business activity.'],settings:['Settings','Local OS preferences and data controls.']};
  function renderNav(){nav.innerHTML=`<div class="os-nav-title">WORKSPACE</div>`+menus.map(([id,icon,label])=>`<button class="os-nav-item ${active===id?'active':''}" data-os="${id}"><span>${icon}</span>${label}</button>`).join('')+`<div class="os-nav-foot"><span class="os-dot"></span> Local workspace</div>`;nav.querySelectorAll('[data-os]').forEach(b=>b.onclick=()=>{active=b.dataset.os;render()})}
  function card(label,value,sub){return `<article class="os-stat"><span>${label}</span><strong>${value}</strong><small>${sub}</small></article>`}
  function table(headers,rows,empty='Nothing here yet.'){return rows.length?`<div class="os-table-wrap"><table class="os-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:`<div class="os-empty">${empty}</div>`}
  function shell(title,sub,actions=''){return `<div class="os-view-head"><div><span class="eyebrow">Zapify OS</span><h2>${title}</h2><p>${sub}</p></div><div class="os-actions">${actions}</div></div>`}
  function dashboard(){const revenue=data.invoices.filter(x=>x.status==='Paid').reduce((a,x)=>a+x.amount,0), pending=data.invoices.filter(x=>x.status!=='Paid').reduce((a,x)=>a+x.amount,0);return shell('Business overview','Everything important at a glance.',`<button class="os-btn primary" data-action="new-lead">+ New lead</button><button class="os-btn" data-action="new-task">+ Task</button>`)+`<div class="os-stats">${card('Customers',data.customers.length,'records')} ${card('Open leads',data.leads.filter(x=>x.status!=='Won').length,'needs follow-up')} ${card('Paid revenue',money(revenue),'recorded in OS')} ${card('Outstanding',money(pending),'unpaid invoices')}</div><div class="os-two"><section class="os-panel"><div class="os-panel-head"><h3>Projects</h3><button class="os-link" data-go="projects">View all</button></div>${data.projects.map(p=>`<div class="os-project"><div><b>${esc(p.name)}</b><small>${esc(p.client)} · ${esc(p.status)}</small></div><strong>${p.progress}%</strong><div class="os-progress"><i style="width:${p.progress}%"></i></div></div>`).join('')}</section><section class="os-panel"><div class="os-panel-head"><h3>Recent activity</h3></div>${data.activity.map(a=>`<div class="os-activity"><span class="os-dot"></span><div><b>${esc(a.text)}</b><small>${esc(a.time)}</small></div></div>`).join('')}</section></div>`}
  function listPage(type){const [title,sub]=pageMeta[type];let rows=[];if(type==='customers')rows=data.customers.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.contact)}</td><td><span class="os-badge">${esc(x.status)}</span></td><td>${money(x.value)}</td></tr>`);if(type==='leads')rows=data.leads.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.source)}</td><td><span class="os-badge">${esc(x.status)}</span></td><td>${money(x.value)}</td></tr>`);if(type==='quotes')rows=data.quotes.map(x=>`<tr><td><b>${esc(x.number)}</b></td><td>${esc(x.client)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td></tr>`);if(type==='invoices')rows=data.invoices.map(x=>`<tr><td><b>${esc(x.number)}</b></td><td>${esc(x.client)}</td><td>${money(x.amount)}</td><td><span class="os-badge">${esc(x.status)}</span></td></tr>`);if(type==='projects')rows=data.projects.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.client)}</td><td>${esc(x.status)}</td><td>${x.progress}%</td></tr>`);if(type==='tasks')rows=data.tasks.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.due)}</td><td>${esc(x.status)}</td><td><button class="os-btn small" data-complete="${x.id}">Complete</button></td></tr>`);const heads={customers:['Customer','Contact','Status','Value'],leads:['Lead','Source','Status','Potential'],quotes:['Quote','Client','Amount','Status'],invoices:['Invoice','Client','Amount','Status'],projects:['Project','Client','Status','Progress'],tasks:['Task','Due','Status','Action']}[type];return shell(title,sub,type==='customers'||type==='leads'||type==='quotes'||type==='tasks'?`<button class="os-btn primary" data-action="new-${type==='customers'?'customer':type.slice(0,-1)}">+ New</button>`:'')+table(heads,rows)}
  function calendar(){return shell('Calendar','Plan the work around your business.','<button class="os-btn primary" data-action="new-task">+ Add task</button>')+`<div class="os-calendar">${['Mon','Tue','Wed','Thu','Fri'].map((d,i)=>`<div><b>${d}</b><span>${23+i} Sep</span><article>${i===0?'Client follow-up':i===1?'Design review':i===2?'Invoice check':i===3?'Project delivery':'Weekly planning'}</article></div>`).join('')}</div>`}
  function analytics(){const total=data.invoices.reduce((a,x)=>a+x.amount,0),paid=data.invoices.filter(x=>x.status==='Paid').reduce((a,x)=>a+x.amount,0);return shell('Analytics','Simple operational metrics from your local workspace.')+`<div class="os-stats">${card('Invoice value',money(total),'all invoices')} ${card('Collected',money(paid),'paid invoices')} ${card('Collection rate',total?Math.round(paid/total*100)+'%':'0%','paid / total')} ${card('Active projects',data.projects.filter(x=>x.status!=='Complete').length,'currently running')}</div><section class="os-panel"><h3>Pipeline</h3><div class="os-bars">${data.leads.map((x,i)=>`<div><span>${esc(x.name)}</span><i style="width:${Math.min(100,30+i*25)}%"></i><b>${money(x.value)}</b></div>`).join('')}</div></section>`}
  function settings(){return shell('Settings','This demo stores its workspace in your browser.')+`<section class="os-panel"><h3>Workspace</h3><p class="os-muted">Zapify OS is ready to connect to Supabase for real authentication, shared records, storage, payments and team access.</p><button class="os-btn" data-action="reset">Reset demo data</button></section>`}
  function render(){renderNav();if(active==='dashboard')view.innerHTML=dashboard();else if(pageMeta[active])view.innerHTML=listPage(active);else if(active==='calendar')view.innerHTML=calendar();else if(active==='analytics')view.innerHTML=analytics();else view.innerHTML=settings();bindActions();stats.innerHTML=''}
  function bindActions(){view.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{active=b.dataset.go;render()});view.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const t=data.tasks.find(x=>x.id==b.dataset.complete);if(t)t.status='Complete';data.activity.unshift({text:`Task completed: ${t.title}`,time:'Just now'});save()});view.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action))}
  function action(a){if(a==='reset'){data=structuredClone(seed);save();return}const now=Date.now();if(a==='new-lead'){const name=prompt('Lead name');if(name){data.leads.unshift({id:now,name,source:'Manual',status:'New',value:0});data.activity.unshift({text:`New lead added: ${name}`,time:'Just now'});save()}}else if(a==='new-task'){const title=prompt('Task');if(title){data.tasks.unshift({id:now,title,due:'Today',status:'Open'});save()}}else if(a==='new-customer'){const name=prompt('Customer name');if(name){data.customers.unshift({id:now,name,contact:'',status:'Active',value:0});save()}}else if(a==='new-quote'){const client=prompt('Client');if(client){data.quotes.unshift({id:now,number:'ZQ-'+String(now).slice(-4),client,amount:0,status:'Draft'});save()}}}
  render();
})();
