const http=require('http');
const fs=require('fs');
const path=require('path');
const root=__dirname,port=Number(process.env.PORT||8080);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.xml':'application/xml; charset=utf-8','.txt':'text/plain; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.pdf':'application/pdf','.webmanifest':'application/manifest+json'};
function safePath(urlPath){const decoded=decodeURIComponent((urlPath||'/').split('?')[0]);const clean=decoded==='/'?'/index.html':decoded;const relative=clean.replace(/^[/\\]+/,'');const full=path.normalize(path.join(root,relative));return full.startsWith(root)?full:null}
function send(res,status,body,type='text/plain; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'X-Content-Type-Options':'nosniff'});res.end(body)}
const server=http.createServer((req,res)=>{if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,'Method not allowed');try{const file=safePath(req.url);if(!file)return send(res,403,'Forbidden');fs.stat(file,(err,st)=>{if(!err&&st.isDirectory()){const indexFile=path.join(file,'index.html');return fs.stat(indexFile,(ie,is)=>{if(ie||!is.isFile())return send(res,404,'Not found');res.writeHead(200,{'Content-Type':types[path.extname(indexFile).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache'});if(req.method==='HEAD')return res.end();fs.createReadStream(indexFile).pipe(res)})}if(err||!st.isFile())return send(res,404,'Not found');res.writeHead(200,{'Content-Type':types[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')return res.end();fs.createReadStream(file).pipe(res)})}catch{send(res,500,'Server error')}});
server.listen(port,'127.0.0.1',()=>console.log(`Zapify running at http://127.0.0.1:${port}`));
