const assert=require('node:assert/strict');
const {templates,allAddons,scrapbookFeatures,calculateOrder}=require('../server/catalog');
assert.equal(Object.keys(templates).length,6);
assert.equal(Object.values(templates).every(t=>t.price===100),true);
const webFeatures=allAddons.filter(x=>x.templates==='all');
assert.equal(webFeatures.length,30);
assert.equal(webFeatures.filter(x=>x.paid).length,15);
assert.equal(webFeatures.filter(x=>!x.paid).length,15);
assert.equal(scrapbookFeatures.length,50);
assert.equal(scrapbookFeatures.every(x=>Array.isArray(x.templates)&&x.templates.includes('scrapbook')),true);
const img='data:image/jpeg;base64,AAAA';
assert.equal(calculateOrder({template:'salon',customization:{images:[img,img,img,img,img]}}).total,100);
assert.equal(calculateOrder({template:'salon',customization:{images:[img,img,img,img,img,img,img]}}).total,130);
assert.equal(calculateOrder({template:'salon',customization:{features:[{id:'sticky-navigation'},{id:'custom-palette'}]}}).total,150);
assert.equal(calculateOrder({template:'scrapbook',customization:{features:[{id:'scrapbook-stickers'},{id:'scrapbook-music'}]}}).total,150);
assert.equal(calculateOrder({template:'salon',customization:{features:[{id:'not-a-real-feature',price:1e-8}]}}).total,100);
assert.throws(()=>calculateOrder({template:'scrapbook',customization:{images:['data:text/plain;base64,AAAA']}}));
console.log('Zapify catalog/payment calculation smoke tests passed.');
