import * as THREE from 'three';
const canvas=document.querySelector('#car3d');
let renderer,scene,camera,car,clock,ready=false;
function makeCar(){const group=new THREE.Group();const bodyMat=new THREE.MeshStandardMaterial({color:0x1a071f,metalness:.82,roughness:.22});const purple=new THREE.MeshStandardMaterial({color:0x6b167f,metalness:.88,roughness:.18});const black=new THREE.MeshStandardMaterial({color:0x09090c,metalness:.7,roughness:.2});const glass=new THREE.MeshStandardMaterial({color:0x101826,metalness:.15,roughness:.08,transparent:true,opacity:.86});const body=new THREE.Mesh(new THREE.BoxGeometry(4.7,1.05,2.05,8,3,8),bodyMat);body.position.y=.82;body.scale.z=1.03;group.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.5,.9,1.65,6,3,6),glass);cabin.position.set(.25,1.58,0);cabin.rotation.z=-.03;group.add(cabin);const hood=new THREE.Mesh(new THREE.BoxGeometry(1.6,.16,1.8),purple);hood.position.set(-1.45,1.36,0);group.add(hood);const bumper=new THREE.Mesh(new THREE.BoxGeometry(.22,.48,1.92),black);bumper.position.x=2.35;bumper.position.y=.58;group.add(bumper);for(const z of [-1,1]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.56,.56,.32,32),black);wheel.rotation.x=Math.PI/2;wheel.position.set(-1.45,.5,z*1.04);group.add(wheel);const wheel2=wheel.clone();wheel2.position.x=1.55;group.add(wheel2)}const grille=new THREE.Mesh(new THREE.BoxGeometry(.08,.35,.8),black);grille.position.set(2.48,.83,0);group.add(grille);const headMat=new THREE.MeshStandardMaterial({color:0xddeeff,emissive:0x8ec7ff,emissiveIntensity:2});for(const z of [-.58,.58]){const h=new THREE.Mesh(new THREE.BoxGeometry(.08,.12,.3),headMat);h.position.set(2.5,1.08,z);group.add(h)}const spoiler=new THREE.Mesh(new THREE.BoxGeometry(.15,.08,1.9),purple);spoiler.position.set(-2.28,1.5,0);group.add(spoiler);return group}
function init(){scene=new THREE.Scene();scene.background=null;camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,100);camera.position.set(7,3.4,8);camera.lookAt(0,1,0);renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;clock=new THREE.Clock();scene.add(new THREE.HemisphereLight(0xdcc8ff,0x100512,2.2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(4,7,6);scene.add(key);const rim=new THREE.PointLight(0xa72cff,16,20);rim.position.set(-4,3,-3);scene.add(rim);car=makeCar();scene.add(car);ready=true;onScroll();animate()}
function onScroll(){if(!ready)return;const hero=document.querySelector('.auto-hero');const r=hero.getBoundingClientRect();const p=Math.min(1,Math.max(0,(innerHeight-r.top)/(r.height+innerHeight*.25)));const eased=p*p*(3-2*p);car.rotation.y=-.25+eased*Math.PI*2.15;car.rotation.x=.05+eased*.08;car.position.y=Math.sin(eased*Math.PI)*.22;car.scale.setScalar(.86+eased*.18);document.documentElement.style.setProperty('--build-progress',eased);const state=eased<.2?'DAMAGE ASSESSMENT':eased<.5?'PANEL REPAIR':eased<.78?'SPRAY & CUSTOMISE':'MIDNIGHT PURPLE BUILD';document.querySelector('#buildState').textContent=state}
function animate(){requestAnimationFrame(animate);if(ready){const t=clock.getElapsedTime();car.position.x=Math.sin(t*.35)*.05;renderer.render(scene,camera)}}addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);onScroll()});
window.addEventListener('load',()=>{try{init()}catch(e){console.error('Autozone Three.js failed',e)}});
document.querySelector('#qform')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const msg=`Hi Zapify Autozone! I would like a quote.%0AName: ${encodeURIComponent(d.get('name'))}%0APhone: ${encodeURIComponent(d.get('phone'))}%0AService: ${encodeURIComponent(d.get('service'))}%0ADetails: ${encodeURIComponent(d.get('message'))}`;window.open(`https://wa.me/27743899657?text=${msg}`,'_blank','noopener,noreferrer')});
