const root=document.documentElement,play=document.querySelector('#playground'),trailLayer=document.querySelector('#trailLayer');let soundOn=false,audioCtx,drag=false,ox=0,oy=0;
const soundBtn=document.querySelector('#sound');function beep(freq=520){if(!soundOn)return;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.06)}
document.querySelector('#blur')?.addEventListener('input',e=>play.style.filter=`blur(${e.target.value/5}px)`);document.querySelector('#glow')?.addEventListener('input',e=>document.querySelector('#orb').style.boxShadow=`0 0 ${e.target.value*3}px #d8b64788`);document.querySelector('#bg')?.addEventListener('change',e=>{play.dataset.bg=e.target.value;const m={stars:'radial-gradient(#8b6d2a55 1px,transparent 1px)',hearts:'radial-gradient(#d9a7a7 2px,transparent 2px)',paws:'radial-gradient(#b69a4b 2px,transparent 2px)',flowers:'radial-gradient(#d7a6b8 2px,transparent 2px)',dots:'radial-gradient(#8f7cff44 2px,transparent 2px)',gold:'linear-gradient(#b9963a22 1px,transparent 1px),linear-gradient(90deg,#b9963a22 1px,transparent 1px)'};play.style.backgroundImage=m[e.target.value];play.style.backgroundSize=e.target.value==='gold'?'35px 35px':'50px 50px'});document.querySelector('#trail')?.addEventListener('change',e=>play.dataset.trail=e.target.value);document.querySelector('#motion')?.addEventListener('change',e=>play.dataset.motion=e.target.value);soundBtn?.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.textContent=soundOn?'🔊 Sound On':'🔇 Sound Off';beep()});document.querySelectorAll('.controls button,.tool-grid button').forEach(b=>b.addEventListener('click',()=>beep(620)));document.querySelector('#reset')?.addEventListener('click',()=>location.reload());document.querySelectorAll('.cursor-choice').forEach(b=>b.addEventListener('click',()=>{document.body.className='cursor-'+b.dataset.cursor;beep(700)}));
play?.addEventListener('pointermove',e=>{if(!trailLayer)return;const type=play.dataset.trail||'sparkle';if(type==='none'||Math.random()>.22)return;const el=document.createElement('span');el.textContent=type==='hearts'?'♥':type==='dots'?'•':'✦';el.style.cssText=`position:absolute;left:${e.offsetX}px;top:${e.offsetY}px;color:#b9963a;font-size:${8+Math.random()*14}px;pointer-events:none;transform:translate(-50%,-50%);animation:trailFade .8s ease forwards`;trailLayer.appendChild(el);setTimeout(()=>el.remove(),800)});
const style=document.createElement('style');style.textContent='@keyframes trailFade{to{opacity:0;transform:translate(-50%,-80%) scale(.2)}}';document.head.appendChild(style);
const ball=document.querySelector('#dragBall');ball?.addEventListener('pointerdown',e=>{drag=true;ball.setPointerCapture(e.pointerId);ox=e.clientX-ball.offsetLeft;oy=e.clientY-ball.offsetTop;ball.style.cursor='grabbing'});ball?.addEventListener('pointermove',e=>{if(!drag)return;const r=play.getBoundingClientRect();ball.style.position='absolute';ball.style.left=Math.max(0,Math.min(r.width-ball.offsetWidth,e.clientX-r.left-ox))+'px';ball.style.top=Math.max(0,Math.min(r.height-ball.offsetHeight,e.clientY-r.top-oy))+'px';ball.style.transform=`perspective(500px) rotateX(${(e.clientY-r.top)/r.height*30-15}deg) rotateY(${(e.clientX-r.left)/r.width*30-15}deg) scale(1.05)`});ball?.addEventListener('pointerup',()=>{drag=false;ball.style.cursor='grab'});
document.querySelector('#comment')?.addEventListener('submit',e=>{e.preventDefault();const n=document.querySelector('#commentName').value.trim()||'Guest',t=document.querySelector('#commentText').value.trim();if(!t)return;const div=document.createElement('div');div.className='comment';div.innerHTML=`<b>${n.replace(/[<>]/g,'')}</b><p>${t.replace(/[<>]/g,'')}</p>`;document.querySelector('#comments').prepend(div);e.currentTarget.reset();beep(740)});

// Extra playground tools
document.querySelectorAll('[data-demo]').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.demo;const effects={magnetic:'magnetic buttons',tilt:'3D tilt',spotlight:'spotlight',ripple:'ripple',orbit:'orbit',typing:'type-on',parallax:'parallax',confetti:'confetti',gradient:'gradient',glass:'glass blur',particles:'particles',pulse:'pulse'};document.body.dataset.activeTool=effects[type]||type;beep(760);if(type==='confetti'){for(let i=0;i<24;i++){const s=document.createElement('span');s.textContent=['✦','◆','●','♥'][i%4];s.style.cssText=`position:fixed;z-index:999;left:${50+(Math.random()-.5)*20}%;top:45%;font-size:${10+Math.random()*18}px;color:#b9963a;pointer-events:none;animation:trailFade ${.7+Math.random()*.8}s ease forwards`;document.body.appendChild(s);setTimeout(()=>s.remove(),1600)}}else if(type==='gradient'){play.style.background='radial-gradient(circle at 20% 20%,#fff7d0,#fffdf8 35%,#e6d6a7)'}else if(type==='glass'){play.style.backdropFilter='blur(14px)';play.style.background='rgba(255,255,255,.7)'}else if(type==='particles'){play.style.backgroundImage='radial-gradient(#b9963a66 1px,transparent 1px)';play.style.backgroundSize='24px 24px'}else if(type==='pulse'){document.querySelector('#orb').animate([{transform:'scale(1)'},{transform:'scale(1.15)'},{transform:'scale(1)'}],{duration:900,iterations:3})}else{play.animate([{transform:'scale(1)'},{transform:'scale(1.015)'},{transform:'scale(1)'}],{duration:500})}}));
