(()=>{
 const body=document.body,type=body.dataset.template||'salon';if(window.top!==window.self)document.querySelector('.top .cta')?.remove();
 const presets={salon:[{name:'Blush',accent:'#e32976',bg:'#fff2f7',ink:'#19191f'},{name:'Sage',accent:'#789b88',bg:'#f1f7f2',ink:'#17221b'},{name:'Noir',accent:'#111',bg:'#f2f2f3',ink:'#111'}],mechanic:[{name:'Volt',accent:'#ffb44c',bg:'#111a20',ink:'#fff'},{name:'Redline',accent:'#ef4b45',bg:'#211619',ink:'#fff'},{name:'Electric',accent:'#38bdf8',bg:'#0d1820',ink:'#fff'}],restaurant:[{name:'Terracotta',accent:'#c56d4a',bg:'#f7eee7',ink:'#241713'},{name:'Olive',accent:'#89956a',bg:'#f2f4e9',ink:'#20251a'},{name:'Midnight',accent:'#9c7bd9',bg:'#17131e',ink:'#fff'}],photographer:[{name:'Mono',accent:'#111',bg:'#f1f1f1',ink:'#111'},{name:'Rose',accent:'#d76a91',bg:'#fff1f7',ink:'#22151c'},{name:'Cobalt',accent:'#4f78c8',bg:'#eef4ff',ink:'#101827'}],construction:[{name:'Safety',accent:'#e0ad2e',bg:'#202a22',ink:'#fff'},{name:'Orange',accent:'#e56e32',bg:'#2c211c',ink:'#fff'},{name:'Signal Blue',accent:'#4f8ebc',bg:'#152433',ink:'#fff'}],scrapbook:[{name:'Candy',accent:'#d65d92',bg:'#fff8fb',ink:'#2b1e27'},{name:'Sunny',accent:'#d29b2f',bg:'#fff8df',ink:'#332a18'},{name:'Ocean',accent:'#3f83a7',bg:'#edf8ff',ink:'#182a36'}]};
 const slots=[...document.querySelectorAll('[data-upload-slot]')],defaults=slots.map(e=>e.style.backgroundImage||''),hero=document.querySelector('[data-hero-image]'),heroDefault=hero?.style.backgroundImage||'';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function apply(cfg={}){
  const p=(presets[type]||[])[Number(cfg.preset||0)]||(presets[type]||[])[0];if(!p)return;const r=document.documentElement;
  const accent=cfg.accentColor||cfg.primaryColor||p.accent,bg=cfg.backgroundColor||p.bg,ink=cfg.textColor||p.ink;
  r.style.setProperty('--tpl-accent',accent);r.style.setProperty('--tpl-secondary',cfg.secondaryColor||bg);r.style.setProperty('--tpl-bg',bg);r.style.setProperty('--tpl-ink',ink);r.style.setProperty('--tpl-button',cfg.buttonColor||accent);r.style.setProperty('--tpl-body',cfg.fontFamily||'Inter,system-ui,sans-serif');r.style.setProperty('--tpl-heading',cfg.headingFont||cfg.fontFamily||'Inter,system-ui,sans-serif');r.style.setProperty('--tpl-font-size',(cfg.fontSize||16)+'px');r.style.setProperty('--card-radius',(cfg.radius??22)+'px');r.style.setProperty('--tpl-shadow',`0 18px 50px rgba(0,0,0,${Math.max(0,Math.min(80,cfg.shadow??40))/100*.45})`);r.style.setProperty('--tpl-spacing',((cfg.spacing||10)/10));r.style.setProperty('--hero-overlay-alpha',String((cfg.heroOverlay??35)/100));
  body.className=[...body.classList].filter(x=>!x.startsWith('feature-')&&!x.startsWith('nav-')).join(' ');(cfg.features||[]).forEach(f=>{const id=typeof f==='string'?f:f.id;if(id)body.classList.add('feature-'+id)});body.classList.toggle('no-animations',cfg.animations===false);body.classList.toggle('sticky-nav',cfg.stickyNav!==false);body.classList.toggle('transparent-header',!!cfg.transparentHeader);body.classList.add('nav-'+(cfg.navStyle||'minimal'),'hero-layout-'+(cfg.heroLayout||'split'),'button-'+(cfg.buttonStyle||'pill'),'nav-position-'+(cfg.navPosition||'top'));r.style.setProperty('--button-radius',cfg.buttonStyle==='square'?'4px':cfg.buttonStyle==='rounded'?'12px':cfg.buttonStyle==='outline'?'12px':'999px');
  document.querySelectorAll('[data-brand]').forEach(e=>{if(cfg.business)e.textContent=cfg.business});document.querySelectorAll('[data-headline]').forEach(e=>{if(cfg.headline)e.textContent=cfg.headline});document.querySelectorAll('[data-services]').forEach(e=>{if(cfg.services)e.textContent=cfg.services});document.querySelectorAll('[data-about]').forEach(e=>{if(cfg.about)e.textContent=cfg.about});document.querySelectorAll('[data-cta]').forEach(e=>{if(cfg.cta)e.textContent=cfg.cta;e.href=cfg.bookingUrl||e.getAttribute('href')});
  if(cfg.logoImage){document.querySelectorAll('.logo').forEach(e=>{e.textContent='';e.style.background=`url("${cfg.logoImage}") center/contain no-repeat`;e.style.minHeight='44px';e.style.minWidth='150px'})}
  const imgs=[...(cfg.images||[])];slots.forEach((e,i)=>{const img=imgs[i];e.style.backgroundImage=img?`url("${img}")`:defaults[i]||'';e.style.backgroundSize='cover';e.style.backgroundPosition=cfg.imagePosition||'center';e.classList.toggle('has-image',!!img)});if(hero){hero.style.backgroundImage=cfg.heroImage?`url("${cfg.heroImage}")`:heroDefault;hero.style.backgroundPosition=cfg.imagePosition||'center'}
  document.querySelectorAll('.sections .tile').forEach((e,i)=>{const visible=i===0?cfg.showServices:(i===1?cfg.showAbout:cfg.showContact);e.style.display=visible===false?'none':''});document.querySelector('.template-gallery')?.style.setProperty('display',cfg.showGallery===false?'none':'');
  const existing=document.getElementById('zapifyDynamicSections');if(existing)existing.remove();const wrap=document.createElement('section');wrap.id='zapifyDynamicSections';wrap.className='sections zapify-dynamic';const defs=[['showAbout','About','about'],['showTestimonials','Testimonials','testimonials'],['showFaq','FAQ','faq'],['showPricing','Pricing','pricing'],['showContact','Contact','contact'],['showNewsletter','Newsletter','newsletter'],['showBlog','Latest news','blog'],['showTimeline','Timeline','timeline']];defs.forEach(([flag,title,kind])=>{if(cfg[flag]){const a=document.createElement('article');a.className='tile dynamic-'+kind;a.innerHTML=`<span class="eyebrow">${esc(title)}</span><h2>${esc(cfg.business||'Your website')}</h2><p>${kind==='contact'?'Send an enquiry, call or message us.':kind==='pricing'?'Flexible options can be presented here.':kind==='faq'?'Frequently asked questions can be published here.':kind==='timeline'?'A chronological story can be displayed here.':kind==='blog'?'News, updates and articles can be published here.':kind==='newsletter'?'Join the newsletter for updates.':kind==='testimonials'?'“Beautiful experience.” · “Exactly what we wanted.”':'Tell your story and give visitors useful information.'}</p>`;wrap.appendChild(a)}});if(wrap.children.length)document.querySelector('main')?.appendChild(wrap);
  let footer=document.querySelector('.brand-credit');if(footer&&cfg.footerText)footer.textContent=cfg.footerText;
  const old=document.getElementById('zapifyCustomCss');if(old)old.remove();if(cfg.customCss){const s=document.createElement('style');s.id='zapifyCustomCss';s.textContent=cfg.customCss.slice(0,10000);document.head.appendChild(s)}
  const oldMeta=document.getElementById('zapifySeoDescription');if(oldMeta)oldMeta.remove();if(cfg.seoDescription){const m=document.createElement('meta');m.id='zapifySeoDescription';m.name='description';m.content=cfg.seoDescription;document.head.appendChild(m)}if(cfg.seoTitle)document.title=cfg.seoTitle;if(cfg.noIndex){let m=document.querySelector('meta[name="robots"]');if(!m){m=document.createElement('meta');document.head.appendChild(m)}m.content='noindex,nofollow'}if(cfg.analyticsId&&!document.getElementById('zapifyAnalytics')){const ga=document.createElement('script');ga.id='zapifyAnalytics';ga.async=true;ga.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(cfg.analyticsId);document.head.appendChild(ga);const gs=document.createElement('script');gs.textContent=`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config',${JSON.stringify(cfg.analyticsId)})`;document.head.appendChild(gs)}if(cfg.ogImage){let og=document.getElementById('zapifyOgImage');if(!og){og=document.createElement('meta');og.id='zapifyOgImage';og.setAttribute('property','og:image');document.head.appendChild(og)}og.content=cfg.ogImage}if(cfg.faviconImage){let l=document.getElementById('zapifyFavicon');if(!l){l=document.createElement('link');l.id='zapifyFavicon';l.rel='icon';document.head.appendChild(l)}l.href=cfg.faviconImage}
  if(type==='scrapbook')renderScrapbook(cfg);
  const whatsapp=cfg.whatsappButton&&cfg.whatsapp?cfg.whatsapp.replace(/\D/g,''):'';let wb=document.getElementById('zapifyWhatsapp');if(wb)wb.remove();if(whatsapp){wb=document.createElement('a');wb.id='zapifyWhatsapp';wb.href=`https://wa.me/${whatsapp}`;wb.target='_blank';wb.rel='noopener';wb.textContent='WhatsApp';document.body.appendChild(wb)}
 }
 function renderScrapbook(cfg){let host=document.getElementById('zapifyScrapPages');if(!host){host=document.createElement('div');host.id='zapifyScrapPages';host.className='scrapbook-pages';document.querySelector('.scrap')?.appendChild(host)}host.innerHTML='';const pages=cfg.scrapbook?.pages||[];const title=cfg.scrapbook?.title||cfg.business||'Your Story';document.querySelectorAll('[data-headline]').forEach(e=>{if(cfg.headline)e.textContent=cfg.headline});pages.forEach((p,i)=>{const el=document.createElement('article');el.className='scrap-page-preview'+(p.private?' is-private':'');el.innerHTML=`<div class="scrap-page-head"><span>${esc(p.category||'Memory')}</span><b>${esc(p.date||'')}</b></div><h2>${esc(p.title||`Memory ${i+1}`)}</h2><p>${esc(p.text||'')}</p>${p.location?`<small>⌖ ${esc(p.location)}</small>`:''}${p.sticker?`<span class="page-sticker">${esc(p.sticker)}</span>`:''}<div class="page-photos"></div></article>`;const photo=el.querySelector('.page-photos');(p.images||[]).forEach(src=>{const im=document.createElement('img');im.src=src;im.alt='Memory photo';photo.appendChild(im)});host.appendChild(el)});if(!pages.length)host.innerHTML=`<article class="scrap-page-preview"><h2>${esc(title)}</h2><p>Add memories from the editor.</p></article>`}
 let data={};try{data=JSON.parse(localStorage.getItem('zapifyTemplatePreview')||'{}')}catch{}apply(data);window.addEventListener('message',e=>{if(e.data?.type==='zapify-preview')apply(e.data.config||{})});window.ZAPIFY_TEMPLATE_PRESETS=presets[type]||[];
})();
