(function(){
 const body=document.body, root=document.documentElement;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const defaults={salon:{accent:'#e32976',bg:'#fff2f7',ink:'#19191f',font:'DM Sans, sans-serif',heading:'DM Sans, sans-serif'},mechanic:{accent:'#ffb44c',bg:'#111a20',ink:'#fff',font:'DM Sans, sans-serif',heading:'Impact, sans-serif'},restaurant:{accent:'#c56d4a',bg:'#f7eee7',ink:'#241713',font:'system-ui,sans-serif',heading:'Georgia, serif'},photographer:{accent:'#111',bg:'#f1f1f1',ink:'#111',font:'Inter, sans-serif',heading:'Inter, sans-serif'},construction:{accent:'#e0ad2e',bg:'#202a22',ink:'#fff',font:'DM Sans, sans-serif',heading:'Impact, sans-serif'},scrapbook:{accent:'#d65d92',bg:'#fff8fb',ink:'#2b1e27',font:'Georgia, serif',heading:'Georgia, serif'}};
 const type=body.dataset.template||'salon', d=defaults[type]||defaults.salon;
 const set=(n,v)=>root.style.setProperty(n,v);
 const apply=cfg=>{
   cfg=cfg||{};set('--accent',cfg.accentColor||cfg.primaryColor||d.accent);set('--bg',cfg.backgroundColor||d.bg);set('--ink',cfg.textColor||d.ink);set('--font',cfg.fontFamily||d.font);set('--heading',cfg.headingFont||d.heading);set('--font-size',(cfg.fontSize||16)+'px');set('--radius',(cfg.radius??22)+'px');set('--space',String((cfg.spacing||10)/10));set('--button-radius',cfg.buttonStyle==='square'?'4px':cfg.buttonStyle==='rounded'?'12px':cfg.buttonStyle==='outline'?'12px':'999px');
   body.classList.toggle('no-animations',cfg.animations===false);body.classList.toggle('nav-hidden',cfg.navStyle==='hidden');
   document.querySelectorAll('[data-brand]').forEach(e=>{if(cfg.business)e.textContent=cfg.business});document.querySelectorAll('[data-headline]').forEach(e=>{if(cfg.headline)e.textContent=cfg.headline});document.querySelectorAll('[data-services]').forEach(e=>{if(cfg.services)e.textContent=cfg.services});document.querySelectorAll('[data-about]').forEach(e=>{if(cfg.about)e.textContent=cfg.about});document.querySelectorAll('[data-cta]').forEach(e=>{if(cfg.cta)e.textContent=cfg.cta;if(cfg.bookingUrl)e.href=cfg.bookingUrl});
   const imgs=[...(cfg.images||[])];document.querySelectorAll('[data-upload-slot]').forEach((e,i)=>{if(imgs[i])e.style.backgroundImage='url("'+imgs[i]+'")'});const hero=document.querySelector('[data-hero-image]');if(hero&&cfg.heroImage)hero.style.backgroundImage='url("'+cfg.heroImage+'")';
   if(cfg.logoImage){document.querySelectorAll('.logo').forEach(e=>{e.textContent='';e.style.background='url("'+cfg.logoImage+'") center/contain no-repeat';e.style.minHeight='44px';e.style.minWidth='150px'})}
   const flags=['showAbout','showServices','showGallery'];const tiles=document.querySelectorAll('.sections .tile');if(tiles[0]&&cfg.showServices===false)tiles[0].style.display='none';if(tiles[1]&&cfg.showAbout===false)tiles[1].style.display='none';if(tiles[2]&&cfg.showContact===false)tiles[2].style.display='none';const gal=document.querySelector('.template-gallery');if(gal&&cfg.showGallery===false)gal.style.display='none';
   const old=document.getElementById('zapifyDynamic');if(old)old.remove();const defs=[['showTestimonials','Testimonials'],['showFaq','FAQ'],['showPricing','Pricing'],['showContact','Contact'],['showNewsletter','Newsletter'],['showBlog','Latest news'],['showTimeline','Timeline']];const chosen=(cfg.features||[]).map(x=>typeof x==='string'?x:x.id);const wrap=document.createElement('section');wrap.id='zapifyDynamic';wrap.className='dynamic-sections';defs.forEach(([flag,title])=>{if(cfg[flag]||chosen.includes(flag.replace(/^show/,'').replace(/[A-Z]/g,m=>'-'+m.toLowerCase()).replace(/^-/,'')+'-section')){const a=document.createElement('article');a.className='tile';a.innerHTML='<span class="eyebrow">'+esc(title)+'</span><h2>'+esc(cfg.business||'Your website')+'</h2><p>'+esc(title==='Contact'?'Give visitors a clear way to enquire or book.':title+' content can be added here.')+'</p>';wrap.appendChild(a)}});if(wrap.children.length)document.querySelector('main')?.appendChild(wrap);
   const footer=document.querySelector('.brand-credit');if(footer&&cfg.footerText)footer.textContent=cfg.footerText;
   let custom=document.getElementById('zapifyCustomCss');if(custom)custom.remove();if(cfg.customCss){custom=document.createElement('style');custom.id='zapifyCustomCss';custom.textContent=String(cfg.customCss).slice(0,12000);document.head.appendChild(custom)}
   let wb=document.getElementById('zapifyWhatsapp');if(wb)wb.remove();if(cfg.whatsappButton&&cfg.whatsapp){const n=String(cfg.whatsapp).replace(/\D/g,'');if(n){wb=document.createElement('a');wb.id='zapifyWhatsapp';wb.className='whatsapp';wb.href='https://wa.me/'+n;wb.target='_blank';wb.rel='noopener';wb.textContent='WhatsApp';document.body.appendChild(wb)}}
   if(type==='scrapbook')renderScrap(cfg);
 };
 function renderScrap(cfg){const host=document.getElementById('scrapPages');if(!host)return;host.innerHTML='';const pages=cfg.scrapbook?.pages||[];set('--page-bg',cfg.scrapbook?.pageColor||'#fff');const title=cfg.scrapbook?.title||cfg.business||'Your Story';if(!pages.length){host.innerHTML='<article class="scrap-page-preview"><h2>'+esc(title)+'</h2><p>Add memories from the editor.</p></article>';return}pages.forEach((p,i)=>{const el=document.createElement('article');el.className='scrap-page-preview'+(p.private?' is-private':'');el.innerHTML='<div class="scrap-page-head"><span>'+esc(p.category||'Memory')+'</span><b>'+esc(p.date||'')+'</b></div><h2>'+esc(p.title||('Memory '+(i+1)))+'</h2><p>'+esc(p.text||'')+'</p>'+(p.location?'<small>⌖ '+esc(p.location)+'</small>':'')+(p.sticker?'<span class="page-sticker">'+esc(p.sticker)+'</span>':'')+'<div class="page-photos"></div>';const photos=el.querySelector('.page-photos');(p.images||[]).forEach(src=>{const im=document.createElement('img');im.src=src;im.alt='Memory photo';photos.appendChild(im)});host.appendChild(el)})}
 let initial={};try{initial=JSON.parse(localStorage.getItem('zapifyTemplatePreview')||'{}')}catch(e){}apply(initial);window.addEventListener('message',e=>{if(e.data&&e.data.type==='zapify-preview')apply(e.data.config||{})});window.ZAPIFY_TEMPLATE_APPLY=apply;
})();
